### ISSUE TITLE
有一个bug，动画没执行完按钮也是可以点击的，因为自定义了点击事件setEnabled(false)时候也会执行onClick

### ISSUE THREAD

**Issue by ZJLeBron** [CTSN/FlodAbleButton#1]
case MotionEvent.ACTION_UP:
                if (canClick && onClickListener != null&& isEnabled()) {
                    onClickListener.onClick(sfb);
                }
在判断中加入isEnable（）条件就ok了。

**Comment by CTSN** [comment]
谢谢了 这个真倒是没注意到

**Comment by ZJLeBron** [comment]
共同进步哈哈
